# fly.toml app configuration file generated for old-star-2515 on 2023-11-15T11:50:29-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "old-star-2515"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
